aws_region                  = "us-east-1"
environment                 = "prod"
vpc_cidr                    = "10.1.0.0/16"
public_subnet_cidrs         = ["10.1.1.0/24", "10.1.2.0/24"]
private_subnet_cidrs        = ["10.1.10.0/24", "10.1.20.0/24"]
availability_zones          = ["us-east-1a", "us-east-1b"]
container_image             = "nginx:alpine"
ecs_cpu                     = 1024
ecs_memory                  = 2048
ecs_app_count               = 3
rds_instance_class          = "db.r6g.xlarge"
rds_allocated_storage       = 100
db_name                     = "bookings_prod"
db_username                 = "postgres"
db_password                 = "ProdComplexSecret987!"
rds_backup_retention_period = 30
rds_deletion_protection     = true
